# Configuration for automating releases and generating release notes.
# This file uses semantic versioning (Major.Minor.Patch) based on labels applied to pull requests.

# Define the naming conventions for releases.
name-template: "v$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"

# Define how version bumps are determined based on PR labels.
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "feat"
      - "feature"
      - "enhancement"
      - "minor"
  patch:
    labels:
      - "bug"
      - "fix"
      - "bugfix"
      - "hotfix"
      - "patch"
      - "refactor"
      - "docs"
      - "documentation"
      - "auto-update"
  default: "minor" # Default version bump when no matching labels are found.

exclude-labels:
  - "no-release"

# Include only changes from the target branch for the release.
filter-by-commitish: true

# Categorize pull requests and issues in the release notes based on their labels.
categories:
  - title: "💥 Breaking Changes"
    labels:
      - "breaking-change"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "feat"
      - "major"
      - "minor"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bug"
      - "bugfix"
      - "hotfix"
      - "patch"
  - title: "🛠️ Refactoring"
    labels:
      - "refactor"
  - title: "📝 Documentation"
    labels:
      - "docs"
      - "documentation"
  - title: "🤖 Automated Updates"
    labels:
      - "auto-update"

# Template for formatting individual change entries in the release notes.
change-template: |
  <details>
    <summary>$TITLE (@$AUTHOR, #$NUMBER)</summary>
  $BODY
  </details>

# Template for the overall release notes structure.
template: |
  # 🚀 Release $RESOLVED_VERSION

  $CHANGES

  **Changelog automatically generated by [GitHub Actions](https://github.com/actions).**

# Text replacements to clean up unwanted content from release notes.
replacers:
  - search: '/(?<=---\\s)\\s*^#.*(Renovate configuration|Configuration)(?:.|\\n)*?This PR has been generated .*/gm'
    replace: "" # Removes unnecessary Renovate configuration details.
  - search: '/\\[!\\[[^\\]]*Renovate\\][^\\]]*\\](\\([^)]*\\))?\\s*\\n+/gm'
    replace: "" # Removes Renovate bot banner images.
