name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! 💡  
        Please provide as much detail as possible to help us evaluate your request.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more information? (Optional)
      placeholder: ex. email@example.com

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Provide a concise summary of the feature or enhancement.
      placeholder: Briefly describe your idea.

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      description: Explain the problem this feature solves or the benefits it provides.
      placeholder: Describe why this feature is needed.

  - type: textarea
    id: details
    attributes:
      label: Detailed Description
      description: Provide a detailed explanation of the feature. Include use cases, examples, or mockups if applicable.
      placeholder: Add any relevant details to help us understand your request.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or Workarounds
      description: Have you considered any alternative solutions or workarounds? If so, please describe them.
      placeholder: Share alternative ideas or current workarounds.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/thecloudsolutions/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
