name: Bug Report
description: Report a bug or problem.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! 🐛

        Please provide as much detail as possible to help us address the issue effectively.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more information? (Optional)
      placeholder: ex. email@example.com

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what went wrong and what you expected to happen.
      placeholder: Describe the problem here.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Specify the version of our software you were using when the issue occurred.
      placeholder: ex. 1.0.0, 1.1.0-beta, or Other
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Operating Systems
      description: Which operating system(s) were you using when the issue occurred? Select all that apply.
      options:
        - label: Windows
        - label: Linux
        - label: macOS
        - label: Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any logs, error messages, or output that might help diagnose the issue.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/thecloudsolutions/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
